Add Promise return type for proxy function
Compiling this project in TypeScript gave the following error:
```
error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).
declare function proxy(proxyParams: ProxyParams): Promise
```
This commit tries to fix this error without being explicit with the return type.